;HEADER FOR 16F818
TMR0	EQU		1
STATUS	EQU		3
PORTA	EQU		5H
PORTB	EQU		6H
TRISA	EQU		85H
TRISB	EQU		86H
ADCON0	EQU		1FH
ADCON1	EQU		9FH
ADRES	EQU		1EH
CARRY	EQU		0
ZEROBIT	EQU		2
OPTION_R	EQU		81H
OSCCON	EQU		8FH
COUNT	EQU		20H

		LIST	P=16F818
		ORG		0
		GOTO	START
__CONFIG	H'3F10'

;SUBROUTINE SECTION
ON		BSF		PORTB,0
		GOTO	BEGIN
OFF		BCF		PORTB,0
		GOTO	BEGIN
OFFALL	MOVLW	.0
		MOVWF	PORTB
		GOTO	BEGIN
OFF2	BCF		PORTB,1
		GOTO	BEGIN
OFF3	BCF		PORTB,2
		GOTO	BEGIN
OFF4	BCF		PORTB,3
		GOTO	BEGIN
OFF5	BCF		PORTB,4
		GOTO	BEGIN
;CONFIGURATION SECTION
START	BSF		STATUS,5
		MOVLW	B'11111111'
		MOVWF	TRISA
		MOVLW	B'00000100'
		MOVWF	ADCON1
		MOVLW	B'00000000'
		MOVWF	TRISB
		MOVLW	B'00000000'
		MOVWF	OSCCON
		MOVLW	B'00000111'
		MOVWF	OPTION_R
		BCF		STATUS,5
		BSF		ADCON0,0
		CLRF	PORTA
		CLRF	PORTB
;PROGRAM STARTS
BEGIN	BSF		ADCON0,2
WAIT1	BTFSC	ADCON0,2
		GOTO	WAIT1
		MOVF	ADRES,W
		SUBLW	.51
		BTFSC	STATUS,CARRY
		GOTO	OFF
		BSF		PORTB,0
		BSF		ADCON0,2
WAIT2	BTFSC	ADCON0,2
		GOTO	WAIT2
		MOVF	ADRES,W
		SUBLW	.102
		BTFSC	STATUS,CARRY
		GOTO	OFF2
		BSF		PORTB,1
		BSF		ADCON0,2
WAIT3	BTFSC	ADCON0,2
		GOTO	WAIT3
		MOVF	ADRES,W
		SUBLW	.153
		BTFSC	STATUS,CARRY
		GOTO	OFF3
		BSF		PORTB,2
		BSF		ADCON0,2
WAIT4	BTFSC	ADCON0,2
		GOTO	WAIT4
		MOVF	ADRES,W
		SUBLW	.204
		BTFSC	STATUS,CARRY
		GOTO	OFF4
		BSF		PORTB,3
		BSF		ADCON0,2
WAIT5	BTFSC	ADCON0,2
		GOTO	WAIT5
		MOVF	ADRES,W
		SUBLW	.240
		BTFSC	STATUS,CARRY
		GOTO	OFF5
		BSF		PORTB,4
		GOTO	BEGIN
		END