TMR0 		EQU 1 		;means TMR0 is file 1.
STATUS 		EQU 3 		;means STATUS is file 3.
PORTA 		EQU 5 		;means PORTA is file 5.
PORTB 		EQU 6 		;means PORTB is file 6.
TRISA 		EQU 85H 	;TRISA (the PORTA I/O selection) is file 85H
TRISB 		EQU 86H 	;TRISB (the PORTB I/O selection) is file 86H
OPTION_R 	EQU 81H 	;the OPTION register is file 81H
ZEROBIT 	EQU 2 		;means ZEROBIT is bit 2.
COUNT 		EQU 0CH 	; COUNT is file 0C, a register to count events.
;*********************************************************
LIST 	P=16F84 ;we are using the 16F84.
ORG 	0 	;the start address in memory is 0
GOTO 	START ;goto start!
;******************************************************************
; Configuration Bits
__CONFIG H'3FF0' ;selects LP oscillator, WDT off, PUT on,
;Code Protection disabled.
;*****************************************************
;SUBROUTINE SECTION.
; 1 second delay.
DELAY1 	CLRF 	TMR0 	;START TMR0.
LOOPA 	MOVF 	TMR0,W 	;READ TMR0 INTO W.
		SUBLW 	.32 	;TIME - 32
		BTFSS 	STATUS,ZEROBIT ; Check TIME-W¼0
		GOTO 	LOOPA 	;Time is not¼32.
		RETLW 	0 		;Time is 32, return.
; 0.5 second delay.

DELAYP1 CLRF 	TMR0 	;START TMR0.
LOOPB 	MOVF 	TMR0,W 	;READ TMR0 INTO W.
		SUBLW 	.3	;TIME - 16
		BTFSS 	STATUS,ZEROBIT ; Check TIME-W¼0
		GOTO 	LOOPB 	;Time is not¼16.
		RETLW 	0 	;Time is 16, return.
CLRDISP	CLRF	PORTA
		MOVLW	0H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	1
		MOVWF	PORTB
		CALL	CLOCK
		CALL	DELAYP1
		RETLW	0
CLOCK	BSF		PORTA,2
		NOP
		BCF		PORTA,2
		NOP
		RETLW	0

A		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	1H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

BB		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	2H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

C		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	3H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

D		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

E		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

F		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	6H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

G		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	7H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

H		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	8H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

I		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	9H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

J		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0AH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

K		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0BH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

L		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0CH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

M		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0DH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

N		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0EH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

O		MOVLW	2
		MOVWF	PORTA
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0FH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

P		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

Q		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	1H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

R		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	2H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

S		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	3H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

T		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

U		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

V		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	6H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

W		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	7H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

X		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	8H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

Y		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	9H
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

Z		MOVLW	2
		MOVWF	PORTA
		MOVLW	5H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0AH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0

COMA	MOVLW	2
		MOVWF	PORTA
		MOVLW	2H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0CH
		MOVWF	PORTB
		CALL	CLOCK
		RETLW	0
;*********************************************************
;CONFIGURATION SECTION.
START 	BSF 	STATUS,5 ;Turns to Bank1.
		MOVLW 	B'00000000' 	;5bits of PORTA are I/P
		MOVWF 	TRISA
		MOVLW 	B'00000000'
		MOVWF 	TRISB 		;PORTB is OUTPUT
		MOVLW 	B'00000111' 	;Prescaler is /256
		MOVWF 	OPTION_R 	;TIMER is 1/32 secs.
		BCF 	STATUS,5 	;Return to Bank0.
		CLRF 	PORTA 		;Clears PortA.
		CLRF 	PORTB 		;Clears PortB.
;DISPLAY CONFIGURATION
		MOVLW	03H
		MOVWF	PORTB
		CALL	CLOCK		;DEFAULT	8BIT MODE
		CALL	DELAYP1
		MOVLW	02H
		MOVWF	PORTB
		CALL	CLOCK
		CALL	DELAYP1
		MOVLW	02H			;SET 4 BIT
		MOVWF	PORTB
		CALL	CLOCK
		CALL	DELAYP1
		MOVLW	08H			;LINE 2, 5*7 DOT
		MOVWF	PORTB
		CALL	CLOCK		
		CALL	DELAYP1
		MOVLW	0H			;DISPLAY ON/CURSOR OFF
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0CH
		MOVWF	PORTB
		CALL	CLOCK
		CALL	DELAYP1
		MOVLW	0H			;INCREMENT CURSOR
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	6H
		MOVWF	PORTB
		CALL	CLOCK
		
;PROGRAM	STARTS
BEGIN		CALL	CLRDISP
		CLRF	PORTA
		MOVLW	8H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	0H
		MOVWF	PORTB
		CALL	CLOCK
	
		CALL	H
		CALL	I
		CALL	COMA
		CALL	DELAY1
FLASH	CALL	CLRDISP
		MOVLW	8H
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	4H
		MOVWF	PORTB
		CALL	CLOCK
		
		CALL	S
		CALL	U
		CALL	N
		CALL	N
		CALL	O
		CALL	L
		CLRF	PORTA
		MOVLW	0CH
		MOVWF	PORTB
		CALL	CLOCK
		MOVLW	2H
		MOVWF	PORTB
		CALL	CLOCK
		CALL	DELAYP1

		CALL	E
		CALL	DELAYP1
		CALL	L
		CALL	DELAYP1
		CALL	E
		CALL	DELAYP1
		CALL	C
		CALL	DELAYP1
		CALL	T
		CALL	DELAYP1
		CALL	R
		CALL	DELAYP1
		CALL	O
		CALL	DELAYP1
		CALL	N
		CALL	DELAYP1
		CALL	I
		CALL	DELAYP1
		CALL	C	
		CALL	DELAYP1
		CALL	S
		CALL	DELAY1
		GOTO	FLASH

		GOTO	BEGIN
		END
